Allow to sort the XML & fixes
bbqsrc/xmlem pull request #3
Opened 2022-12-01 14:22 UTC by hoijui

The sorting is probably quite buggy,
but for a first trial with a simple SVG from Inkspace,
it does what I want and the SVG is still valid
and looks the same.

2022-12-01 14:37 UTC, hoijui commented
I also have the code for xml-pretty ready already.

2022-12-01 15:22 UTC, bbqsrc requested changes
A few things I'd like changed if you don't mind. 😄

2022-12-01 15:22 UTC, bbqsrc commented on src/document.rs
> +pub fn node2ordinal(node: &Node) -> u8 {
Make this a to_ordinal method on Node itself.

2022-12-01 15:22 UTC, bbqsrc commented on src/document.rs
> +            el_attrs.sort_by(ord_q_name);
This one is simple enough it can just be a closure.

2022-12-01 15:22 UTC, bbqsrc commented on src/document.rs
> +            );
This should be logging not a println; if we don't already have the `tracing` dependency, let's add it.

2022-12-02 07:20 UTC, hoijui commented
Should be done now

2022-12-02 13:50 UTC, merged

2022-12-02 13:50 UTC, bbqsrc commented
Thanks :)